# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 The HiSchool! Project
# Generated by Django 1.11.2 on 2017-06-13 06:58
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations

'''
Add the Administrators, the Teachers, and the Students group.
These groups will be used later on to grant specific permissions on views.
'''


def add_group(group_name):
    new_group = Group(name=group_name)
    new_group.save()


def add_new_group(apps, schema_editor):
    add_group('Administrators')
    add_group('Teachers')
    add_group('Students')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_new_group),
    ]
