# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 The HiSchool! Project
# Generated by Django 1.11.2 on 2017-06-24 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170613_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('view_account', 'Can view the list of registered accounts'),)},
        ),
    ]
