# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='part',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='part',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='session',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_modified',
        ),
    ]
